pp4_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('thoughts.urls'), name='thoughts-urls'),
    path("select2/", include("django_select2.urls")),
    path('accounts/', include('allauth.urls')),
]

thoughts/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.ThoughtList.as_view(), name='home'),
    path('add', views.ThoughtList.add_thought, name='add'),
    path('edit/<thought_id>', views.ThoughtList.edit_thought, name='edit'),
    path(
        'delete/<object_type>/<object_id>',
        views.ThoughtList.delete,
        name='delete'
        ),
    path(
        'like/<object_type>/<object_id>',
        views.ThoughtList.like_toggle,
        name='like'
        ),
    path('view/<thought_id>', views.ThoughtDetail.as_view(), name='view'),
    path('user/<user_id>', views.UserDetail.view_user, name='user'),
]

thoughts/models.py
from django.db import models
from django.utils.html import format_html
from django.contrib import admin
from django.contrib.auth.models import User
from django.utils import timezone
from colorfield.fields import ColorField


class Tag(models.Model):
    """
    Database model for tags, to be attached
    to user-submitted thoughts
    """
    name = models.CharField(max_length=40)
    text_color = ColorField(default='#FF0000')
    bg_color = ColorField(default='#FF0000')

    # Shows tag colors in admin menu
    @admin.display
    def colored_name(self):
        """
        Returns tag as formatted html, includes
        text and background color
        """
        return format_html(
            '<span class="btn" style="color: {}; ' +
            'background-color: {}">{}</span>',
            self.text_color,
            self.bg_color,
            self.name,
        )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Thought(models.Model):
    """
    Database model for user-submitted thoughts
    """
    title = models.CharField(
        max_length=96, null=False, blank=False)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='thoughts'
        )
    content = models.TextField(max_length=400, null=False, blank=False)
    time = models.TimeField(default=timezone.now, null=True, blank=True)
    anonymous = models.BooleanField(null=False, blank=False, default=True)
    # auto_now_add applies only on creation while auto_now applies on update
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(
        User,
        related_name="thought_likes",
        blank=True
        )
    tags = models.ManyToManyField(Tag, blank=True)

    class Meta:
        ordering = ['-date_created']

    def number_of_likes(self):
        return self.likes.count()

    def number_of_comments(self):
        return self.comment_thought.count()

    def __str__(self):
        return self.title


class Comment(models.Model):
    """
    Database model for comments, to be attached to thoughts
    """
    thought = models.ForeignKey(
        Thought,
        on_delete=models.CASCADE,
        related_name="comment_thought"
        )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comment_author'
        )
    content = models.TextField(max_length=280, null=False, blank=False)
    anonymous = models.BooleanField(null=False, blank=False, default=False)
    date_created = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(
        User,
        related_name="comment_likes",
        blank=True
        )

    class Meta:
        ordering = ['date_created']

    def number_of_likes(self):
        return self.likes.count()

    def __str__(self):
        return str(self.author.get_short_name() + ": " + self.content)

thoughts/forms.py
from django import forms
from .models import Thought, Comment, Tag
from thoughts.widgets import TagWidget, TimeWidget
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column, Submit


class ThoughtForm(forms.ModelForm):
    """
    Form for submitting thoughts, uses custom widgets
    """
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=TagWidget(attrs={'id': 'form-tag-widget'}),
        required=False
        )

    time = forms.TimeField(
        widget=TimeWidget,
        required=False
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column('title', css_class='form-group col-md-8 mb-0 px-1'),
                Column('time', css_class='form-group col-md-4 mb-0 px-1'),
                css_class='form-row'
            ),
            'content',
            'tags',
            'anonymous',
            Submit('submit', 'Submit Thought')
        )

    class Meta:
        model = Thought
        fields = ['title', 'content', 'time', 'anonymous', 'tags']
        widgets = {
            # Reduces size of text area
            'content': forms.Textarea(attrs={'rows': 4}),
            }


class CommentForm(forms.ModelForm):
    """
    Simple form for submitting comments
    """
    class Meta:
        model = Comment
        fields = ['content', 'anonymous']
        widgets = {
            # Reduces size of text area
            'content': forms.Textarea(attrs={'rows': 3}),
        }

thoughts/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.views import generic, View
from django.contrib import messages
from django.db.models import Sum
from django.http import JsonResponse
from .models import Thought, User, Comment
from .forms import ThoughtForm, CommentForm
from .filters import ThoughtFilter


class ThoughtList(generic.ListView):
    """
    Displays the main page featuring the latest user-submitted thoughts
    """
    model = Thought
    queryset = Thought.objects.order_by('-date_created')
    template_name = 'thoughts/view_thoughts.html'
    paginate_by = 8

    def get_queryset(self):
        """
        Filters the default queryset using filters.ThoughtFilter
        """
        queryset = super().get_queryset()
        thought_filter = ThoughtFilter(self.request.GET, queryset=queryset)
        return thought_filter.qs

    def get_context_data(self, **kwargs):
        """
        Sets context to include thoughtFilter,
        allows us to include details of our search
        """
        context = super().get_context_data(**kwargs)
        thought_filter = ThoughtFilter(
            self.request.GET,
            queryset=self.get_queryset()
            )
        context['filter'] = thought_filter
        return context

    def add_thought(request):
        """
        Creates a new thought using the contents of ThoughtForm
        with the logged in user as the author
        """
        if not user_is_logged_in(request.user):
            messages.add_message(
                request,
                messages.ERROR,
                'Please sign in to post thoughts.'
                )
            return redirect('account_login')

        if request.method == 'POST':
            form = ThoughtForm(request.POST)
            if form.is_valid():
                # Sets the author to current user before saving
                thought = form.save(commit=False)
                thought.author = request.user
                thought.save()
                # Saves tags (many-to-many relationship)
                form.save_m2m()
                messages.add_message(
                    request,
                    messages.SUCCESS,
                    'Thought successfully posted!'
                    )
                return redirect('home')
        form = ThoughtForm()
        context = {
            'form': form
        }
        return render(request, 'thoughts/add_thought.html', context)

    def edit_thought(request, thought_id):
        """
        Edits an existing thought with the specified id
        using the form ThoughtForm
        """
        thought = get_object_or_404(Thought, id=thought_id)

        # Ensures only the owner/superuser may edit
        if not user_is_owner_or_superuser(request.user, thought.author):
            messages.add_message(
                request,
                messages.ERROR,
                'Only the owner may edit this post.'
                )
            return redirect('home')

        if request.method == 'POST':
            form = ThoughtForm(request.POST, instance=thought)
            if form.is_valid():
                form.save()
                messages.add_message(
                    request,
                    messages.SUCCESS,
                    'Thought successfully edited.'
                    )
                return redirect('home')
        form = ThoughtForm(instance=thought)
        context = {
            'form': form
        }
        return render(request, 'thoughts/edit_thought.html', context)

    def delete(request, object_type, object_id):
        """
        Deletes thought or comment with the specified id
        """
        model = Thought if object_type == 'thought' else Comment
        obj = get_object_or_404(model, id=object_id)
        # Ensures only the owner/superuser may delete
        if not user_is_owner_or_superuser(request.user, obj.author):
            messages.add_message(
                request,
                messages.ERROR,
                'Only the owner may delete this post.'
                )
        else:
            obj.delete()
            messages.add_message(
                request,
                messages.SUCCESS,
                f'{object_type.capitalize()} successfully deleted.'
                )
        if object_type == 'comment':
            return redirect(f'/view/{obj.thought.pk}')
        else:
            return redirect('home')

    def like_toggle(request, object_id, object_type):
        """
        Adds user to 'likes' of specified thought or comment,
        if already present removes user instead.
        Supports ajax calls to update like count.
        """
        model = Thought if object_type == 'thought' else Comment

        obj = get_object_or_404(model, id=object_id)
        user = request.user
        # If not logged in, redirects to login page
        if not user_is_logged_in(user):
            messages.add_message(
                    request,
                    messages.ERROR,
                    'Please sign in to leave likes.'
                    )
            if request.is_ajax:
                return JsonResponse(
                    {"error": "Please sign in to leave likes."}, status=401
                    )
            else:
                return redirect('account_login')

        # If AJAX, return if liked and like count
        if request.is_ajax:
            if obj.likes.filter(id=user.id).exists():
                obj.likes.remove(user)
                liked = False
            else:
                obj.likes.add(user)
                liked = True

            return JsonResponse(
                {'liked': liked, 'likes_count': obj.number_of_likes()}
                )
        # Else redirect home with success message
        else:
            if obj.likes.filter(id=user.id).exists():
                obj.likes.remove(user)
                messages.add_message(
                    request,
                    messages.SUCCESS,
                    f'Succesfully unliked a {object_type}!'
                    )
            else:
                obj.likes.add(user)
                messages.add_message(
                    request,
                    messages.SUCCESS,
                    f'Succesfully liked a {object_type}!'
                    )
            if object_type == 'comment':
                return redirect(f'/view/{obj.thought.pk}')
            else:
                return redirect('home')


class ThoughtDetail(View):
    """
    Displays a single thought and related comments
    """
    def get(self, request, *args, **kwargs):
        """
        Gets a thought based on kwarg thought_id.
        Includes comments, if liked by user and comment form
        """
        thought_id = kwargs.get('thought_id')
        queryset = Thought.objects
        thought = get_object_or_404(queryset, id=thought_id)
        comments = thought.comment_thought.order_by('date_created')
        liked = False
        if thought.likes.filter(id=self.request.user.id).exists():
            liked = True
        context = {
                "thought": thought,
                "comments": comments,
                "liked": liked,
                "comment_form": CommentForm(),
            }
        return render(request, "thoughts/thought_detail.html", context)

    def post(self, request, *args, **kwargs):
        """
        Posts a comment on the thought with
        the logged in user as the comment author
        """
        # Ensures user is logged in, redirects to login
        if not user_is_logged_in(request.user):
            messages.add_message(
                request,
                messages.ERROR,
                'Please sign in to leave comments.'
                )
            return redirect('account_login')

        thought_id = kwargs.get('thought_id')
        queryset = Thought.objects
        thought = get_object_or_404(queryset, id=thought_id)
        comments = thought.comment_thought.order_by('date_created')
        liked = False
        if thought.likes.filter(id=self.request.user.id).exists():
            liked = True

        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment_form.instance.author = request.user
            comment = comment_form.save(commit=False)
            comment.thought = thought
            comment.author = request.user
            comment.save()
            messages.add_message(
                request, messages.SUCCESS,
                'Successfully left a comment.'
                )
            return redirect(f'../view/{comment.thought.pk}')
        else:
            comment_form = CommentForm()
            messages.add_message(
                request, messages.ERROR,
                'Comment was not posted.'
                )

        context = {
                "thought": thought,
                "comments": comments,
                "liked": liked,
                "comment_form": CommentForm(),
            }
        return render(request, "thoughts/thought_detail.html", context)


class UserDetail(User):
    """
    Display a user profile containing the amount of
    posts and likes given/received by a specified user
    """
    def view_user(request, user_id):
        """
        Returns context containing a user,
        likes given and likes received based on a user id
        """
        user = get_object_or_404(User, id=user_id)

        # All likes on user thoughts +  comments
        likes_given = user.thought_likes.all().count()
        + user.comment_likes.all().count()

        # Returns the amount of likes from the user posts/comments
        thought_likes = user.thoughts.aggregate(
            Sum('likes')
            )['likes__sum']
        comment_likes = user.comment_author.aggregate(
            Sum('likes')
            )['likes__sum']
        # int(value or 0) as safeguard, can return Nonetype if empty

templates/thoughts/add_thought.html
{% extends 'base.html' %}

{% block content %}

{% load static %}
{% load crispy_forms_tags %}

<div class="row my-4 mx-0">
    <div class="col-lg-4 offset-lg-4 col-md-6 offset-md-3 col-sm-8 offset-sm-2 col-10 offset-1">
        <h1 class="text-center">Add new thought:</h1>

        <!-- Form to create new thought -->
        <form method="post" action="add">
            {% csrf_token %}
            {% crispy form %}
        </form>
    </div>
</div>

<!-- Script to enable Select2 widget for tags -->
<script src="{% static 'js/enable_form_tag_widget.js' %}"></script>

{% endblock %}

templates/thoughts/edit_thought.html
{% extends 'base.html' %}

{% block content %}

{% load static %}
{% load crispy_forms_tags %}

<div class="row my-4 mx-0">
    <div class="col-lg-4 offset-lg-4 col-md-6 offset-md-3 col-sm-8 offset-sm-2 col-10 offset-1">
        <h1 class="text-center">Edit thought:</h1>

        <!-- Form to edit a thought -->
        <form method="post">
            {% csrf_token %}
            {% crispy form %}
        </form>
    </div>
</div>

<!-- Script to enable Select2 widget for tags -->
<script src="{% static 'js/enable_form_tag_widget.js' %}"></script>

{% endblock %}

templates/thoughts/view_thoughts.html
{% extends 'base.html' %}

{% block content %}

{% load static %}
{% load pagination_tags %}

<div class="text-center py-2">
    <div class="row mx-0">
        <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1 col-sm-12 offset-sm-0 my-4">
            <!-- Introductory blurb, first page only-->
            {% if page_obj.number == 1 %}
                <!-- User logged in -->
                {% if user.is_authenticated %}
                    <h1>Hello {{user.username}}!</h1>
                    <p class="lead py-2">
                        Have any thoughts to share? We're all ears!
                    </p>
                    <!-- 'Add new thought' button -->
                    <a href="/add">
                        <div class="btn btn-primary btn-lg">Share a new thought</div>
                    </a>
                <!-- Not logged in -->
                {% else %}
                    <div class="mb-4">
                        <h1>Welcome!</h1>
                        <p class="lead">
                            Have thoughts you rarely get a chance to share?<br>
                            This is the place to share them.
                        </p>
                        <p class="mb-3 col-lg-6 offset-lg-3 col-md-8 offset-md-2 fst-italic">
                            Capture those fleeting moments of inspiration.<br>
                            Share anonymously or embrace your identity.<br>
                            Discover a community of like-minded dreamers.
                        </p>
                        <p class="mb-4 fw-bold">
                            Join the community to post, comment, and leave likes on posts!
                        </p>
                        <div>
                            <a href="{% url 'account_login' %}" class="btn btn-primary me-2">Log in</a>
                            <span class="text-muted">or</span>
                            <a href="{% url 'account_signup' %}" class="btn btn-secondary ms-2">Sign up</a>
                        </div>
                    </div>
                {% endif %}
                <hr class="mt-4">
            {% endif %}
        </div>
        <!-- Text above thoughts/search results -->
        {% if filter.is_searching %}
            <!-- First page, search results -->
            {% if page_obj.number == 1 %}   
                {% if filter.qs.count > 0 %} 
                    <h2>Found {{filter.qs.count}} search results!</h2>
                {% endif %}
            {% else %}
                <!-- Subsequent search pages -->
                <h2>Viewing search result page {{page_obj.number}} of {{paginator.num_pages}}:</h2>
            {% endif %}
        {% else %}
            <!-- First page, non-search -->
            {% if page_obj.number == 1 %} 
                <h2>Here are the most recent thoughts:</h2>
            {% else %}
                <!-- Subsequent non-search pages -->
                <h2>Viewing page {{page_obj.number}} of {{paginator.num_pages}}:</h2>
            {% endif %}
        {% endif %}
    </div>
</div>

<div class="row mx-0 text-center">
    <div class="col-xxl-4 offset-xxl-4 col-lg-6 offset-lg-3 col-md-8 offset-md-2 col-sm-10 offset-sm-1">
        {% csrf_token %}
        <!-- Displays all thoughts, hides author if anonymous -->
        {% for thought in thought_list %}
            <div class="card center mt-3">
                <div class="card-body">
                    <h3 class="card-title">
                        <!-- Title -->
                        <a href="/view/{{thought.id}}"><strong>{{thought.title}}</strong></a>
                    </h3>
                    <h4 class="card-subtitle mb-2 text-body-secondary">
                        <!-- Author (By: [User] [(You)?] at [Time]) -->
                        {% if thought.anonymous %}
                            By: Anonymous 
                        {% else %}
                            By: <a href="/user/{{thought.author.pk}}">{{thought.author}} </a>
                        {% endif %}
                        {% if request.user == thought.author %}
                            (You)
                        {% endif %}
                        {% if thought.time%}
                            at <strong>{{thought.time}}</strong>
                        {% endif %}
                    </h4>
                    <hr>
                    <!-- Content -->
                    <div class="content-container">
                        <p class="card-text pt-1 pb-3">{{thought.content | linebreaksbr }} </p>
                    </div>
                    <!-- Tags -->
                    <div class="tag-container">
                        {% for tag in thought.tags.all %}
                            <a href="/?tags={{tag.pk}}" aria-label="Search by tag '{{tag.name}}'">{{ tag.colored_name }}</a>
                        {% endfor %}
                    </div>
                    <hr>
                    <!-- Displays amount of likes and comments -->
                    <div class="container-fluid">
                        <div class="row py-0 my-0">
                            <div class="col-sm-4 py-2">
                                <a  href="/like/thought/{{thought.id}}" class="like-button link-underline link-underline-opacity-0" aria-label="Like thought"
                                data-obj-type="thought"
                                data-obj-id="{{ thought.id }}">
                                    {% if request.user in thought.likes.all %}
                                        <i class="fa-solid fa-heart"></i>
                                    {% else %}
                                        <i class="fa-regular fa-heart"></i>
                                    {% endif %}
                                    {{ thought.number_of_likes }} 
                                </a>| 
                                <a href="/view/{{thought.id}}" class="link-underline link-underline-opacity-0" aria-label="View comment">
                                    <i class="fa-regular fa-comment-dots"></i> {{ thought.number_of_comments }}
                                </a>
                            </div>
                            <!-- Edit/Delete buttons -->
                            <div class="col-sm-6 offset-sm-2">
                                {% if request.user == thought.author or request.user.is_superuser %}
                                <a href="/edit/{{thought.id}}" class="btn btn-outline-secondary" aria-label="Edit thought">
                                    <i class="fa-regular fa-pen-to-square"></i> Edit
                                </a>
                                <!-- Delete button triggers modal through JS, follows href if JS disabled-->
                                <a href="/delete/thought/{{thought.id}}" class="btn btn-outline-danger btn-delete"
                                data-delete-type="thought"
                                data-delete-id="{{ thought.id }}"
                                data-delete-title='"{{ thought.title }}"'>
                                    <i class="fa-regular fa-trash-can"></i> Delete
                                </a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <br>
            {% empty %}
            <br>
            <h3>No thoughts found, head empty...</h3>
        {% endfor %}
    </div>
</div>

<!-- Pagination heavily inspired by https://stackoverflow.com/a/46329564 by Rob L -->
{% if is_paginated %}
<div class="row mb-4 mx-0">
    <div class="col-lg-12">
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                <!-- 'First' and 'Previous' button -->
                {% if page_obj.has_previous %}
                <li><a href="?{% url_replace request 'page' 1 %}"
                    class="page-link">&laquo; First</a></li>
                <li><a href="?{% url_replace request 'page' page_obj.previous_page_number %}"
                    class="page-link">&lsaquo; Prev</a></li>
                {% endif %}

                <!-- If 3 pages away from start, create left ellipsis  -->
                {% if page_obj.number|add:'-2' > 1 %}
                <li><a href="?{% url_replace request 'page' page_obj.number|add:'-3' %}"
                    class="page-link">&hellip;</a></li>
                {% endif %}
            
                <!-- Show available pages within range  -->
                {% for i in page_obj.paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="active page-link"><span>{{ i }} <span class="sr-only">(current page)</span></span></li>
                    {% elif i > page_obj.number|add:'-3' and i < page_obj.number|add:'3' %}
                        <li><a class="page-link" href="?{% url_replace request 'page' i %}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
            
                <!-- If 3 pages away from end, create right ellipsis  -->
                {% if page_obj.paginator.num_pages > page_obj.number|add:'2' %}
                <li><a class="page-link" href="?{% url_replace request 'page' page_obj.number|add:'3' %}">&hellip;</a></li>
                {% endif %}

                <!-- 'Next' and 'Last' button -->
                {% if page_obj.has_next %}
                <li><a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}">Next &rsaquo;</a></li>
                <li><a class="page-link" href="?{% url_replace request 'page' paginator.num_pages %}">Last &raquo;</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>
{% endif %}

<!-- Script to update like count -->
<script src="{% static 'js/toggle_like_ajax.js' %}"></script>
<!-- Script to enable 'btn-delete' modal -->
<script src="{% static 'js/enable_delete_modal.js' %}"></script>

{%endblock%}